config/routes.rb
Healthdy::Application.routes.draw do
  resources :logins

  resources :students
  
  root :to => "logins#new"

end

app/models/login.rb
class Login < ActiveRecord::Base
	belongs_to :student
	validates :swipe, :presence => true

end

app/models/student.rb
class Student < ActiveRecord::Base
    	  
	has_many :logins
  #in case a student loses a dining card and gets a new one, both need to be linked to the student
  has_many :cards

  #attr_accessible :firstname, :lastname, :diningcard
	
	validates :firstname, :presence => true
	validates :lastname, :presence => true
	#validates :diningcard, :presence => true, :length => 6
	#validates :hopeid, :presence => true, :length => 9
	
	def fullname
		"#{firstname} #{lastname}"
	end
		
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  # GET /logins
  # GET /logins.xml
  def index
    @logins = Login.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @logins }
    end
  end
  
  # GET /logins/1
  # GET /logins/1.xml
  def show
    @login = Login.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @login }
    end
  end

  # GET /logins/new
  # GET /logins/new.xml
  def new
    @login = Login.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @login }
    end
  end

  # GET /logins/1/edit
  def edit
    @login = Login.find(params[:id])
  end

  # POST /logins
  # POST /logins.xml
  def create
    @login = Login.new(params[:login])
    # Deletes the first and last characters of the swiped card id string
    @login.swipe = @login.swipe.delete(";,?")
    
    respond_to do |format|
      if @login.save
        format.html { redirect_to(@login, :notice => 'Login was successful.') }
        format.xml  { render :xml => @login, :status => :created, :location => @login }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @login.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /logins/1
  # PUT /logins/1.xml
  def update
    @login = Login.find(params[:id])

    respond_to do |format|
      if @login.update_attributes(params[:login])
        format.html { redirect_to(@login, :notice => 'Login was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @login.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.xml
  def destroy
    @login = Login.find(params[:id])
    @login.destroy

    respond_to do |format|
      format.html { redirect_to(logins_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.xml
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @students }
    end
  end

  # GET /students/1
  # GET /students/1.xml
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @student }
    end
  end

  # GET /students/new
  # GET /students/new.xml
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.xml
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to(@student, :notice => 'Student was successfully created.') }
        format.xml  { render :xml => @student, :status => :created, :location => @student }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @student.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.xml
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to(@student, :notice => 'Student was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @student.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.xml
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to(students_url) }
      format.xml  { head :ok }
    end
  end

end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Health Dynamics Attendance App</title>
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>

<script>
// From http://strugglingwithruby.blogspot.com/2009/04/using-javascript-with-ruby-on-rails.html
// Sets the form focus to the first element found in forms[0] that is a textfield or text area
function setFocus() {
// Bail if no form on page
if (document.forms[0] == null) return;

// Iterate though elements
for (var i = 0; i < document.forms[0].elements.length; i++) {
  e = document.forms[0].elements[i];
  if ((e.type == "text") || (e.type == "textarea")) {
    e.focus();
//    e.value = "";
    break;
  }
}
}

</script>

</head>
<body onload="setFocus()" id="app">
	<div id="banner">
		<h1><%= @page_title || "Health Dynamics Attendance" %></h1>
	</div>
	<div id="columns">
		<div id="side">
			<%= link_to 'New login', new_login_path %><br />
			<%= link_to 'All class logins', logins_path %><br />
			<%= link_to 'New student', new_student_path %><br />
			<%= link_to 'List all Hope College students', students_path %><br />
		</div>
		<div id="main">
			<%= yield %>
		</div>
	</div>
</body>
</html>

app/views/logins/_form.html.erb
<%= form_for(@login) do |f| %>
  <% if @login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% @login.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Card Number<br />
    <%= f.text_field :swipe %>
  </div>

  <br />

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logins/edit.html.erb
<h1>Editing login</h1>

<%= render 'form' %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/index.html.erb
<h1>Class Session Logins</h1>

<% @logins = Login.all(:order => 'created_at DESC') %>

<table>
  <tr>
	<th>Student</th>
	<th>Edit</th>
	<th>Section</th>
    <th>Card</th>
    <th>Logged In</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Destroy</th>
  </tr>

<% @logins.each do |login| %>
  <tr>
	<% if student = Student.find_by_diningcard(login.swipe) %>
	<% @studentid = student.id %>
	<% section = student.section %>
	<% student = student.lastname + ", " + student.firstname %>
	<td><%= student %></td>
	<td><%= link_to 'Edit', edit_student_path(@studentid) %></td>
	<% else student = "* NO NAME"%>
	<td><%= student %></td>
	<td><%= link_to 'New', new_student_path %> </td>
	<% end %>
	<td><%= section %></td>
    <td><%= login.swipe %></td> 
	<% t = login.created_at %>
    <td><%= t.strftime("%a, %b %d %H:%M %Z") %></td>
    <td><%= link_to 'Show', login %></td>
    <td><%= link_to 'Edit', edit_login_path(login) %></td>
    <td><%= link_to 'Destroy', login, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/logins/new.html.erb
<h1>New Login</h1>
<h2>Please swipe card now</h2>

<%= render 'form' %>

<br />

<%= link_to 'Back', logins_path %>

app/views/logins/show.html.erb
<% if student = Student.find_by_diningcard(@login.swipe) %>
<h2><%= student.firstname + " " + student.lastname + " successfully logged in!" %></h2>
<% else student = "No Record"; end %>

<table>
	<tr>
		<th>Card Number</th>
		<th>Name</th>
		<th>Section</th>
        <th>Date/Time</th>
	</tr>
	<tr>
		<td><%= @login.swipe %></td>
		<% student = Student.find_by_diningcard(@login.swipe) %>
		<% login = Login.last %>
		<% login.student_id = student.id %>
		<% login.save %>
				
		<td><%= student.fullname %></td>
		<td><%= student.section %></td>
		<td><%= @login.created_at %></td>
	</tr>
</table>

<br />

<%= link_to 'New Login', new_login_path %>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    First Name<br />
    <%= f.text_field :firstname %>
  </div>

  <div class="field">
    Middle Initial<br />
    <%= f.text_field :middleinitial %>
  </div>

  <div class="field">
    Last Name<br />
    <%= f.text_field :lastname %>
  </div>

  <div class="field">
    Card Number<br />
    <%= f.text_field :diningcard %>
  </div>

  <div class="field">
    Hope I.D. Number<br />
    <%= f.text_field :hopeid %>
  </div>

  <div class="field">
    Email<br />
    <%= f.text_field :email %>
  </div>

  <div class="field">
    Section<br />
    <%= f.radio_button :section, '1' %>
	<%= f.label '1 (8:30am)'%>
    <%= f.radio_button :section, '2' %>
	<%= f.label '2 (9:30am)'%>
  </div>

  <br />

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <tr>
    <th>Lastname</th>
    <th>Firstname</th>
    <th>Card Number</th>
    <th>Hope ID</th>
	<th>Email</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>

<% @students.sort! { |a,b| a.lastname.downcase <=> b.lastname.downcase } %>
<% @students.each do |student| %>
  <tr>
    <td><%= student.lastname %></td>
    <td><%= student.firstname %></td>
    <td><%= student.diningcard %></td>
    <td><%= student.hopeid %></td>
    <td><%= student.email %></td>
    <td><%= link_to 'Show', student %></td>
    <td><%= link_to 'Edit', edit_student_path(student) %></td>
    <td><%= link_to 'Destroy', student, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First Name:</b>
  <%= @student.firstname %>
</p>

<p>
  <b>Middle Initial:</b>
  <%= @student.middleinitial %>
</p>

<p>
  <b>Last Name:</b>
  <%= @student.lastname %>
</p>

<p>
  <b>Card Number:</b>
  <%= @student.diningcard %>
</p>

<p>
  <b>Hope ID Number:</b>
  <%= @student.hopeid %>
</p>

<p>
  <b>Email:</b>
  <%= @student.email %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>